name: Release

# Add permissions block at the top level
permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: build-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: dodgecoin.exe
            asset_name: dodgecoin-windows-x64.zip
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: dodgecoin
            asset_name: dodgecoin-linux-x64.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: dodgecoin
            asset_name: dodgecoin-macos-arm64.tar.gz

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create release archive
        shell: bash
        run: |
          mkdir release
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release/
          cp -r assets release/
          cd release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../release.zip *
          else
            tar -czf ../release.tar.gz *
          fi

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release.*
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
